### ISSUE TITLE
Brew version is out of sync

### ISSUE THREAD

**Issue by jetjager** [kitlangton/zio-app#11]
It looks like the version released to brew is 0.1.14 while the latest release is 0.2.0, is this a feature or a bug ?

**Comment by kitlangton** [comment]
An incredible feature! 😄 

But, in seriousness, it's actually intended. The CLI doesn't necessarily get updated at the same time as the library, so I'll only bump it when the bin changes. Sort of a weird set-up, but it's nice to have all the code co-located.
