### ISSUE TITLE
Seems to require vite global install

### ISSUE THREAD

**Issue by stevewillcock** [kitlangton/zio-app#2]
Hi,

This looks interesting, thanks for the efforts! Running through the instructions I get a failure finding vite (see screenshot). Installing this globally (e.g. `npm install -g vite`) resolves this error. Not sure if this should be added to the instructions or if this should be using the local install of vite via package.json.

<img width="890" alt="image" src="https://user-images.githubusercontent.com/1048426/115672531-c4188180-a39f-11eb-96f1-2d18ed338a1e.png">

**Comment by kitlangton** [comment]
Thanks! Yeah, it should probably use ‘yarn exec vote’. I’ll fix this :)

**Comment by kitlangton** [comment]
I've fixed this 😄 Try `brew upgrade zio-app`

**Comment by stevewillcock** [comment]
Great, thanks, that doesn't require global vite now. The zio-app new experience seems a bit nicer too (hiding the sbt new output?). I'm hitting another issue now though, I'll log that one, cheers :)

**Comment by kitlangton** [comment]
Actually, not using `sbt new` anymore. Using `giter8`'s lib directly :). Much faster.

**Comment by stevewillcock** [comment]
ah, nice! (I haven't looked at the code much yet tbh, just trying it out so far)
